### ISSUE TITLE
neuraloperator import

### ISSUE THREAD

**Issue by apdimier** [neuraloperator/neuraloperator#117]
Hi,
While loading the neuralop module, I get the following error:

Python 3.6.8 (default, Jan 19 2022, 23:28:49) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from neuralop.models import FNO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/localadmin/.local/lib/python3.6/site-packages/neuralop/__init__.py", line 3, in <module>
    from .models import TFNO3d, TFNO2d, TFNO1d, TFNO
  File "/home/localadmin/.local/lib/python3.6/site-packages/neuralop/models/__init__.py", line 1, in <module>
    from .tfno import TFNO3d, TFNO2d, TFNO1d, TFNO
  File "<fstring>", line 1
    (norm=)
Any help would be welcomed
A.

**Comment by JeanKossaifi** [comment]
@apdimier I notice your Python version is very old - can you update to a more recent (Python >3.8)? 
We are not currently compatible with older version.
