### ISSUE TITLE
RuntimeError: The size of tensor a (2) must match the size of tensor b (16) at non-singleton dimension 3

### ISSUE THREAD

**Issue by eshaghi-ms** [neuraloperator/neuraloperator#228]
when I try your code, fourier_1d.py, I have the following error:

Traceback (most recent call last):
  File "/usr/scratch4/zore8312/PyCodes/neuraloperator-master-original/fourier_1d.py", line 203, in <module>
    optimizer.step()
  File "/usr/scratch4/zore8312/mambaforge/envs/torch/lib/python3.11/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/scratch4/zore8312/mambaforge/envs/torch/lib/python3.11/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/scratch4/zore8312/mambaforge/envs/torch/lib/python3.11/site-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/scratch4/zore8312/mambaforge/envs/torch/lib/python3.11/site-packages/torch/optim/adam.py", line 141, in step
    adam(
  File "/usr/scratch4/zore8312/mambaforge/envs/torch/lib/python3.11/site-packages/torch/optim/adam.py", line 281, in adam
    func(params,
  File "/usr/scratch4/zore8312/mambaforge/envs/torch/lib/python3.11/site-packages/torch/optim/adam.py", line 442, in _multi_tensor_adam
    device_grads = torch._foreach_add(device_grads, device_params, alpha=weight_decay)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The size of tensor a (2) must match the size of tensor b (16) at non-singleton dimension 3

**Comment by scaomath** [comment]
Just comment out the `weight_decay` you are good to go. It is a known problem of PyTorch.
