### ISSUE TITLE
(<class 'RuntimeError'>, RuntimeError('Unsupported dtype Half'), <traceback object at 0x7ff3c12f6280>)

### ISSUE THREAD

**Issue by dbl001** [neuraloperator/neuraloperator#289]
I am running on 'MPS' which does not support the datatype Complex64. Initally, I got:
```
RuntimeError: MPS device does not support bmm for non-float inputs

```
So, I tried setting 
```fno_block_precision="half",
```
This generated: 
```
(<class 'RuntimeError'>, RuntimeError('Unsupported dtype Half'), <traceback object at 0x7ff3c12f6280>)
```
<img width="1398" alt="Screenshot 2024-02-20 at 1 35 48 PM" src="https://github.com/neuraloperator/neuraloperator/assets/3105499/6b5c0b89-9929-46c6-8203-81feea6229ef">

**Comment by JeanKossaifi** [comment]
This seems to an issue with PyTorch and mps support rather than neuraloperator library. FNO is built on top of the FFT so complex support is needed. It seems some support may be available in the nightly build of PyTorch: https://github.com/pytorch/pytorch/pull/116630

**Comment by dbl001** [comment]
‘mps’ recently added FFT support which I’m evaluating.  However, it’s limited to complex32.  Will ’neuraloperator’ work with complex32?
Do I need to set ’fno_block_precision = “half” in the class SpectralConv for neural operator to work with complex32?
Setting fno_block_precision = half is what caused the exception I reported.

**Comment by dbl001** [comment]
‘mps’ recently added FFT support which I’m evaluating.  However, it’s limited to complex32.  Will ’neuraloperator’ work with complex32?
Do I need to set ’fno_block_precision = “half” in the class SpectralConv for neural operator to work with complex32?
Setting fno_block_precision = half is what caused the exception I reported.

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/davidlaxer/neuraloperator/scripts/train_darcy.py", line 187, in <module>
    trainer.train(
  File "/Users/davidlaxer/neuraloperator/neuralop/training/trainer.py", line 158, in train
    out  = self.model(**sample)
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1529, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/davidlaxer/neuraloperator/neuralop/models/fno.py", line 253, in forward
    x = self.fno_blocks(x, layer_idx, output_shape=output_shape[layer_idx])
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1529, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/davidlaxer/neuraloperator/neuralop/layers/fno_block.py", line 195, in forward
    return self.forward_with_postactivation(x, index, output_shape)
  File "/Users/davidlaxer/neuraloperator/neuralop/layers/fno_block.py", line 208, in forward_with_postactivation
    x_fno = self.convs(x, index, output_shape=output_shape)
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1529, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/davidlaxer/neuraloperator/neuralop/layers/spectral_convolution.py", line 434, in forward
    x = torch.fft.rfftn(x, norm=self.fft_norm, dim=fft_dims)
RuntimeError: Unsupported dtype Half
python-BaseException

```
<img width="580" alt="Screenshot 2024-02-24 at 8 13 17 AM" src="https://github.com/neuraloperator/neuraloperator/assets/3105499/91a93150-0ded-4e26-b8cd-12c6dfae5802">

**Comment by dbl001** [comment]
pytorch still doesn't support bmm() for device 'mps' which is used in tensorly's einsum().  I created a temporary workaround using numpy.einsum():
```
def _contract_dense(x, weight, separable=False):
    order = tl.ndim(x)
    # batch-size, in_channels, x, y...
    x_syms = list(einsum_symbols[:order])

    # in_channels, out_channels, x, y...
    weight_syms = list(x_syms[1:])  # no batch-size

    # batch-size, out_channels, x, y...
    if separable:
        out_syms = [x_syms[0]] + list(weight_syms)
    else:
        weight_syms.insert(1, einsum_symbols[order])  # outputs
        out_syms = list(weight_syms)
        out_syms[0] = x_syms[0]

    eq = f'{"".join(x_syms)},{"".join(weight_syms)}->{"".join(out_syms)}'

    if not torch.is_tensor(weight):
        weight = weight.to_tensor()

    if x.dtype == torch.complex32:
        # if x is half precision, run a specialized einsum
        return einsum_complexhalf(eq, x, weight)
    else:
        #return tl.einsum(eq, x, weight)
        result_numpy =  np.einsum(eq,x.detach().cpu().numpy(), weight.detach().cpu().numpy())
        result = torch.from_numpy(result_numpy).to(x.device)
        return result
```
