### ISSUE TITLE
regularizer.reset(): AttributeError: 'bool' object has no attribute 'reset'

### ISSUE THREAD

**Issue by dbl001** [neuraloperator/neuraloperator#374]
I set regularizer=True in plot_SFNO_swe.py
```
trainer.train(train_loader=train_loader,
              test_loaders=test_loaders,
              optimizer=optimizer,
              scheduler=scheduler, 
              regularizer=True,
              training_loss=train_loss,
              eval_losses=eval_losses)
...

Traceback (most recent call last):
  File "/Users/davidlaxer/neuraloperator/examples/plot_SFNO_swe.py", line 154, in <module>
    trainer.train(train_loader=train_loader,
  File "/Users/davidlaxer/neuraloperator/neuralop/training/trainer.py", line 180, in train
    regularizer.reset()
AttributeError: 'bool' object has no attribute 'reset'
```

**Comment by dhpitt** [comment]
regularizer should be a PyTorch regualizer object

**Comment by dhpitt** [comment]
Currently fixed in `trainer`: 

```
if self.regularizer:
            self.regularizer.reset()
```
