### ISSUE TITLE
error in latest version

### ISSUE THREAD

**Issue by gokhalen** [neuraloperator/neuraloperator#431]
I tried a one line program 

```
from neuralop.models import FNO
```

using the latest version of the code obtained by cloning the repo. And it gives the error

```
Traceback (most recent call last):
  File "multihead.py", line 1, in <module>
    from neuralop.models import FNO
  File "/mnt/d/FNO/neuraloperator/neuralop/__init__.py", line 5, in <module>
    from .data import datasets, transforms
  File "/mnt/d/FNO/neuraloperator/neuralop/data/__init__.py", line 6, in <module>
    from . import datasets
  File "/mnt/d/FNO/neuraloperator/neuralop/data/datasets/__init__.py", line 4, in <module>
    from .burgers import load_burgers_1dtime
  File "/mnt/d/FNO/neuraloperator/neuralop/data/datasets/burgers.py", line 9, in <module>
    class Burgers1dTimeDataset(PTDataset):
  File "/mnt/d/FNO/neuraloperator/neuralop/data/datasets/burgers.py", line 27, in Burgers1dTimeDataset
    n_tests: list[int],
TypeError: 'type' object is not subscriptable
```
The error goes away when I switch to the tag `0.3.0` using `git checkout tags/0.3.0`. I'm using `Python 3.8.10` and I installed the requirements using `pip install -r requirements.txt`.

**Comment by yjwnb6** [comment]
Hi, I also met the same problem. When I try git checkout tags/0.3.0, I got 'tags/0.3.0' did not match any file(s) known to git.

**Comment by yjwnb6** [comment]
When I run code in examples/ folder, the error also pops out

**Comment by yjwnb6** [comment]
Upgrade python to 3.10 resolved the issue for me
