### ISSUE TITLE
deprecation warning from tensorly

### ISSUE THREAD

**Issue by gokhalen** [neuraloperator/neuraloperator#432]
The following code fails

```
import torch, numpy as np
from torch.utils.data import DataLoader
from neuralop.datasets.tensor_dataset import TensorDataset

ntrain = 100;
nfeat  = 2;

x_torch = torch.from_numpy(np.arange(ntrain*nfeat).reshape(ntrain,nfeat))
y_torch = torch.from_numpy(np.arange(ntrain*nfeat).reshape(ntrain,nfeat))

train_dataset = TensorDataset(x_torch,y_torch)
```

with the error 

```
Traceback (most recent call last):
  File "/mnt/d/FNO/multi-head-fno/testdataset.py", line 11, in <module>
    train_dataset = TensorDataset(x_torch,y_torch)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gokhalen/virtualenv/default/lib/python3.12/site-packages/tensorly/utils/deprecation.py", line 100, in wrapped
    f"{deprecated_name} is deprecated, use {use_instead.__name__} instead."
                                            ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '__name__'. Did you mean: '__ne__'?
```

Any ideas on how to fix?

-Nachiket

**Comment by Penido-exe** [comment]
Could you find a solution?

**Comment by gokhalen** [comment]
No. I downgraded to version 0.3.0 of neuraloperator and python 3.10.12

**Comment by Penido-exe** [comment]
> No. I downgraded to version 0.3.0 of neuraloperator and python 3.10.12

Okay, thank you very much.

**Comment by JeanKossaifi** [comment]
@Penido-exe @gokhalen this is a broken deprecation message: I fixed it but please use `neuralop.data.datasets.tensor_dataset.TensorDataset` instead. `neuralop.datasets` will be completely removed in an upcoming release.

**Comment by dhpitt** [comment]
As of #472, this issue is resolved. @gokhalen , please refer to `neuralop.data.datasets`. Thanks!
