### ISSUE TITLE
Error : numpy.ndarray 

### ISSUE THREAD

**Issue by Parag0206** [neuraloperator/neuraloperator#438]
I am trying to run the Shallow Water Equation code. I am getting the following error:

```
Loading train dataloader at resolution (32, 64) with 200 samples and batch-size=4
Traceback (most recent call last):
  File "/home/test/t.py", line 13, in <module>
    train_loader, test_loaders = load_spherical_swe(n_train=200, batch_size=4, train_resolution=(32, 64),
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuraloperator/neuralop/data/datasets/spherical_swe.py", line 13, in load_spherical_swe
    train_dataset = SphericalSWEDataset(dims=train_resolution, num_examples=n_train, device=device)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neuraloperator/neuralop/data/datasets/spherical_swe.py", line 49, in __init__
    self.solver = ShallowWaterSolver(self.nlat, self.nlon, dt_solver, lmax=lmax, mmax=mmax, grid='equiangular').to(self.device).float()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/ai/lib/python3.12/site-packages/torch_harmonics/examples/shallow_water_equations.py", line 66, in __init__
    self.sht = harmonics.RealSHT(nlat, nlon, lmax=lmax, mmax=mmax, grid=grid, csphase=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/ai/lib/python3.12/site-packages/torch_harmonics/sht.py", line 92, in __init__
    weights = torch.from_numpy(w)
              ^^^^^^^^^^^^^^^^^^^
TypeError: expected np.ndarray (got numpy.ndarray)

```

I believe this is a problem with torch_harmonics?

Can you help me here?

**Comment by dhpitt** [comment]
thanks for raising this! I suggest you open an issue at: https://github.com/NVIDIA/torch-harmonics

**Comment by JeanKossaifi** [comment]
We should make sure our examples run as expected though @dhpitt. @Parag0206 Are you trying to run https://neuraloperator.github.io/dev/auto_examples/plot_SFNO_swe.html#sphx-glr-auto-examples-plot-sfno-swe-py? 

The examples are dynamically built on each PR so it _should_ run with the latest version, can you share a minimum reproducible example, with your version of neuraloperator, PyTorch and torch-harmonics?
